Document: hashcat
Title: Debian hashcat Manual
Author: <insert document author here>
Abstract: This manual describes what hashcat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hashcat/hashcat.sgml.gz

Format: postscript
Files: /usr/share/doc/hashcat/hashcat.ps.gz

Format: text
Files: /usr/share/doc/hashcat/hashcat.text.gz

Format: HTML
Index: /usr/share/doc/hashcat/html/index.html
Files: /usr/share/doc/hashcat/html/*.html
